image: node:12

before_script:
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - echo "$ENV" | tr -d '\r' > .env
  - echo "VERSION=$CI_COMMIT_SHORT_SHA" >> .env
  - apt-get update
  - apt-get install build-essential

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  artifacts:
    name: Built app
    expire_in: 100 years
    paths:
      - dist
  stage: build
  only:
    refs:
      - master
  script:
    - yarn install
    - yarn build

deploy:production:
  stage: deploy
  dependencies:
    - build
  only:
    refs:
      - master
  script:
    - ssh -p22 webhosting@smlouvy.davenov.com "./pre-deploy.sh"
    - scp -p22 -r dist package.json .env yarn.lock webhosting@smlouvy.davenov.com:~/server-new
    - ssh -p22 webhosting@smlouvy.davenov.com "bash post-deploy.sh"
