stages:
  - build
  - deploy

build_app:
  only:
    - master
  stage: build
  image: docker:1.11
  services:
    - docker:dind
  before_script:
    - NICE_TIME=$(echo $CI_COMMIT_TIMESTAMP | cut -f1 -d"+" | tr ":" "-" | tr '[:upper:]' '[:lower:]')
    - export DOCKER_IMAGE_TAG_NEW="${NICE_TIME}-${CI_COMMIT_SHORT_SHA}"
  script:
    - echo "VERSION=$DOCKER_IMAGE_TAG_NEW" > .env
    - echo "REACT_APP_VERSION=$DOCKER_IMAGE_TAG_NEW" >> .env
    - echo "$REACT_APP_ENV" | tr -d '\r' >> .env
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG_NEW
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG_NEW

deploy:stage:
  image: curlimages/curl:7.72.0
  only:
    - master
  stage: deploy
  script:
    - curl "$WEBHOOK_DEPLOY_STAGE$DOCKER_IMAGE_TAG_NEW" -f

deploy:prod:
  image: curlimages/curl:7.72.0
  only:
    - master
  when: manual
  stage: deploy
  script:
    - curl "$WEBHOOK_DEPLOY_PROD$DOCKER_IMAGE_TAG_NEW" -f
