before_script:
  # Setup SSH deploy keys
  # - echo "$ENV" | tr -d '\r' > .env
  - echo "VERSION=$CI_COMMIT_SHORT_SHA" > .env

stages:
  - build
  - deploy

build_app:
  only:
    - tags
  stage: build
  image: docker:1.11
  services:
    - docker:dind
  script:
    # push only for tags
    - '[[ -z $CI_BUILD_TAG ]] && exit 0'
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    #   - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG

deploy:stage:
  only:
    - tags
  stage: deploy
  script:
    - curl "$WEBHOOK_DEPLOY_STAGE=$CI_BUILD_TAG" -f

deploy:prod:
  only:
    - tags
  when: manual
  stage: deploy
  script:
    - curl "$WEBHOOK_DEPLOY_PROD=$CI_BUILD_TAG" -f
