stages:
  - build
  - deploy

build_app:
  only:
    - tags
  stage: build
  image: docker:1.11
  services:
    - docker:dind
  script:
    - echo "VERSION=$CI_COMMIT_TAG" > .env
    - echo "REACT_APP_VERSION=$CI_COMMIT_TAG" >> .env
    - echo "$REACT_APP_ENV" | tr -d '\r' >> .env
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG

deploy:stage:
  image: curlimages/curl:7.72.0
  only:
    - tags
  stage: deploy
  script:
    - curl "$WEBHOOK_DEPLOY_STAGE$CI_BUILD_TAG" -f

deploy:prod:
  image: curlimages/curl:7.72.0
  only:
    - tags
  when: manual
  stage: deploy
  script:
    - curl "$WEBHOOK_DEPLOY_PROD$CI_BUILD_TAG" -f
