version: '3'
services:
  server:
    image: node:12
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; yarn start'
    environment:
      - NODE_ENV=development
      - SERVER_PORT=3001
      - PORT=3000
    ports:
      - '3000:3000'
    working_dir: /usr/src/app
    volumes:
      - nodemodules:/usr/src/app/node_modules
      - .:/usr/src/app
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - ./.dev/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
volumes:
  nodemodules:
    external: true
